### PR TITLE
Fix selenium to use compatible versions

### PR DESCRIPTION
**Pull request by S4more**
Selenium 4.10 removed deprecated code that this library is using.
(https://github.com/SeleniumHQ/selenium/commit/9f5801c82fb3be3d5850707c46c3f8176e3ccd8e).

In my case, it prevented me from running the `open_application` function, since it creates an instance of `WebDriver` and `WebDriver` uses the now-removed parameter `desired_capabilities` in order to initialize the constructor of its parent class, `webdriver.Remote`.

### CODE REVIEW

**Comment by serhatbolsu** [comment]
Can you resolve the conflict and approve again please @S4more

**Comment by HApolonio** [comment]
@S4more - Please resolve the conflicts to allow this Pull Request to be merged.

**Comment by HApolonio** [comment]
@serhatbolsu - Can this be merged now, please?

**Comment by emanlove** [comment]
Looking now @HApolonio ..

**Pull request merged**
