### PR TITLE
add scroll function

### PR DESCRIPTION
**Pull request by testj**
add scroll function to deal wth the scroll problem thar ios version over 7.0

### CODE REVIEW

**Comment by serhatbolsu** [comment]
Hi @testj ,

I got a couple questions.

Did you test this with iOS and Android ? 
Did you face any issues or different behaviour between platforms ? 

Also the keyword names does not suggest it is based from an element. 
Would ```Scroll from element to left``` a better naming?
Thank you

**Comment by testj** [comment]
sorry,response later.In fact,my origin idea is create a common function deal with problem of scroll,but when I see your file has the function like scroll an element,so I reuse your function.It's better to create different function to deal with scroll an element and scroll in the screen.

**Comment by serhatbolsu** [comment]
I am not clear so, is this canceled or you still want to come up with a solution ?

**Comment by serhatbolsu** [comment]
@testj Any plan to follow up this feature ?

**Pull request closed without merging**
