### PR TITLE
update two keyword swipe_left and swipe_right and update documentatio…

### PR DESCRIPTION
**Pull request by haibgit**
update two keyword swipe_left and swipe_right and update documentation find element using class chain

## Implements
update new keyword 
swipe_right
swipe_left

## Fixing
documentation find element using class chain

### CODE REVIEW

**Comment by serhatbolsu** [comment]
@haibgit as far as I remember `swipe_up` `swipe_down` was also working for android, can you confirm please

**Comment by haibgit** [comment]
> @haibgit as far as I remember `swipe_up` `swipe_down` was also working for android, can you confirm please
when I using **scroll_down** and **Scroll Up** for android 9, have an error. 
image

**Comment by haibgit** [comment]
https://github.com/appium/ruby_lib/issues/867 
same issues, KazuCocoa say:
"mobile: scroll is only for xcuitest. [](http://appium.io/docs/en/commands/mobile-command/) "
image

**Comment by serhatbolsu** [comment]
this seems like regarding appium library not this client.

**Pull request closed without merging**
