### PR TITLE
Add tap with number of taps keyword

### PR DESCRIPTION
**Pull request by jvilla17**
## Implements
- Add tap with number of taps keyword for iOS.

### CODE REVIEW

**Comment by serhatbolsu** [comment]
@jvilla17  in the documentation , can you mention `ios only` with the same format used previously

**Comment by jvilla17** [comment]
@serhatbolsu do you mean to the HTML documentation file or within the function definition in the changed file?

**Comment by serhatbolsu** [comment]
within the documentation, you will see some examples from other keywords

**Comment by jvilla17** [comment]
Hi @serhatbolsu, the documentation update is done! 👍🏽

**Comment by serhatbolsu** [comment]
Thank you @jvilla17

**Pull request merged**
