### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by sadikkuzu**
## Implements

* Change `version.py` from 1.6.3 to 1.6.4

### CODE REVIEW

**Comment by vvelusamy1** [comment]
@sadikkuzu  what changes are in version 1.6.4? Noticed one issue and raised https://github.com/serhatbolsu/robotframework-appiumlibrary/issues/344. Is that your version bump deals with this? just a question.

**Comment by sadikkuzu** [comment]
Hi @vvelusamy1 
Thanks for asking.
Well, actually, this pr is about preparation before new release.
Unreleased changes are: https://github.com/serhatbolsu/robotframework-appiumlibrary/compare/1.6.3...master

**Comment by vvelusamy1** [comment]
> 

thanks for the response. we earlier noticed issue https://github.com/appium/appium/issues/16503 and based on that we updated python client or the selenium version as per the comments in that ticket. Not sure the unreleased version have any fixes to use latest RF Appium and RF selenium libraries?

**Comment by henrichsson** [comment]
Hello @serhatbolsu
Really great work on this lib! I just wanted to ask, when can we expect version 1.6.4 release?

**Comment by Reddriver** [comment]
Hi @serhatbolsu, could you release the version above?

**Pull request merged**
