### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by Meallia**
Hi, we're switching to python3 and I had to port this lib.
I do not use iOS so I have no way to check if any functionality is impacted but appium-python-client already supports python 3.5

- switched from ez_setup to setuptools (src/AppiumLibrary -> AppiumLibrary)
- code is now tested under python 2.7, 3.3, 3.4, 3.5 and 3.6

### CODE REVIEW

**Comment by devstrat** [comment]
@serhatbolsu Any chance this one gets addressed? Looking forward for Python3 support, cheers!

**Comment by serhatbolsu** [comment]
I will run the tests this weekend

**Comment by serhatbolsu** [comment]
@Meallia can you clear the code please, I see whole files in commit without any change at all. I have done testing without any change in code, havent seen a problem yet though. 
I am aiming to push this soon

**Comment by xyb** [comment]
@Meallia great job!

@serhatbolsu I suggest modify and merge commits manually if the author is too busy to do this. It will be nice if commits squashed before merge. The files committed but without any code changes are converted from DOS to UNIX format, you can revert the change if you really care about the `truthful` git log. Looking forward for this cool feature.

**Comment by serhatbolsu** [comment]
@Meallia I have check the files, there is no real commit on those other then 
`application_should_be_installed(self, application_id)`
can you copy old files and make a new commit please
I very much like to merge this

**Comment by serhatbolsu** [comment]
@Meallia do you mind checking this again? I intend to merge it after testing?
- need to carry changes over from master

**Comment by serhatbolsu** [comment]
Thank you @Meallia mostly integrated but closing this pr at it is old now

**Pull request closed without merging**
