### PR TITLE
add switch iframe api

### PR DESCRIPTION
**Pull request by KenSrc**
## Add swithc_to_iframe and swtich_to_parent_frame API
When test webview, the web may contain ifram, so we have to switch to the iframe in order to get the element in the iframe. And those API had be implemented by selenium. So I add the keyword to RF_AppiumLibrary.  Sorry for my bad english.

### CODE REVIEW

**Comment by nunessf** [comment]
Any idea if this pull request will be integrated in AppiumLibrary, and when?

**Comment by VinWij** [comment]
I am really confused why this is not implemented into the master branch yet. I'm running into a ton of issues without this, and the change is tiny. In fact, it is so simple that I was left wondering if this was maybe not necessary, that it has built-in ways of dealing with frames, or that frames were maybe extremely unconventional for apps using webviews.

**Comment by studioromeo** [comment]
@serhatbolsu hey, any chance this could be merged?

**Comment by technigirl** [comment]
@serhatbolsu Can this be merged?  Really need this functionality.  Thanks!

**Comment by serhatbolsu** [comment]
@KenSrc thank you

**Pull request merged**
