### PR TITLE
Appium 338

### PR DESCRIPTION
**Pull request by zastress**
## Fixing
Predicate type locator for iOS inside Documentation
https://github.com/serhatbolsu/robotframework-appiumlibrary/issues/388

### CODE REVIEW

**Comment by serhatbolsu** [comment]
Can you update the source as well @zastress , this is an generated document as you know

**Comment by zastress** [comment]
@serhatbolsu I don't know what you mean.

**Comment by emanlove** [comment]
@zastress Liviu, this html is autogenerated and it appears the change was made in the resulting html and not within the source from which the html is generate. Reach out to me and we can resolve.

**Comment by zastress** [comment]
Thanks @emanlove . Solved now :)

**Comment by serhatbolsu** [comment]
Thank you @zastress

**Pull request merged**
