### PR TITLE
Add iOS class chain locator support

### PR DESCRIPTION
**Pull request by erik1510**
Allow users to use iOS class chain in locators. Similar to iOS NSPredicate.

### CODE REVIEW

**Comment by serhatbolsu** [comment]
@erik1510 
Can you link please that this is a common finder strategy also used by other libraries ?

**Comment by idxn** [comment]
@serhatbolsu  any updated?

**Comment by idxn** [comment]
@serhatbolsu I believe a lot of us waiting for this to be merged

**Comment by idxn** [comment]
Thanks a bunch!!!

**Comment by serhatbolsu** [comment]
Just released the version update to pypi @idxn

**Pull request merged**
