### PR TITLE
Fix dependency break  (#417)

### PR DESCRIPTION
**Pull request by rasjani**
Python-Appium-Client 4.0.0 has removed certain features installation breaks currently as current codebase still uses those removed features like TouchAction

### CODE REVIEW

**Comment by filipehba** [comment]
Great fix 👍🏻

**Review by filipehba — APPROVED** [review]

**Comment by HApolonio** [comment]
When will this be merged? But more importantly, when will the root cause be addressed, fixing the reference to TouchAction?

**Review by serhatbolsu — APPROVED** [review]

**Comment by serhatbolsu** [comment]
Thank you @rasjani , looking for support on getting back support post 4.0

**Comment by Wolfe1** [comment]
@Leemur89 There seems to be a release candidate that was created 5 days ago so you could use that for now: https://pypi.org/project/robotframework-appiumlibrary/#history

**Comment by emanlove** [comment]
As Brandon noted I am working on the next release. At this point it is mostly the release notes that I need to put together. Raphael (or anyone else) if you have the time and system to try out the release candidate it would be good to get some feedback.

**Pull request merged**
