### PR TITLE
Added new feature to install app via code

### PR DESCRIPTION
**Pull request by howtoautomateinth**
Please review my code to merge since this one is necessary when someone want to install it using appium

### CODE REVIEW

**Comment by serhatbolsu** [comment]
Hi @howtoautomateinth ,

install app can be a good addition indeed but the way you suggest does not make much use. 
Since you use "current_app" which in order to open session appium automatically installs the app. 

I think in order this method to make sence it can accept "path to app file" (and url if possible).
Please check these in local and discuss more

**Comment by howtoautomateinth** [comment]
so sorry that make you confuse my named variable. :(

my intension is "app_path" equal to "path_to_app" like apk file that we want to install during the test.

I sent this merge request because I found some scenario that I have to remove application and install application during the test.

e.g.

"If App. A have facebook App. it have to open but if it didn't it should open web view"

with this scenario I have to remove app to check behavior and I think this function should help another developer since we already have remove application keyword. :)

Please do not hesitate to give me a comment.

**Comment by serhatbolsu** [comment]
Did you test this in local @howtoautomateinth . I worry that after you uninstall main app, you would not able to install / launch a new one since main thread was dependent on the main app.

Also please mention if this is Android only in keyword documentation.

**Comment by howtoautomateinth** [comment]
Yes,I already have tested on local machine first before sent this merge request. 

Anyway, the main purpose of this one isn't uninstall/ install "main" app during the test ... but for uninstall/install "related" app for main app testing.

like the scenario that I have mention in previous comment.

Oh and this is "Android only" :) I will add it for more clearly in document

**Pull request merged**
