### PR TITLE
handle WebElement locator properly

### PR DESCRIPTION
**Pull request by idxn**
update _element._element_find fx to handle WebElement locator properly

### CODE REVIEW

**Comment by idxn** [comment]
@serhatbolsu Is this possible to be merged? Any comments?

**Comment by idxn** [comment]
@serhatbolsu Any feedback for this? What should I do to get this merged?

**Comment by serhatbolsu** [comment]
Even though it looks broken, returning a list variable might break other methods. I will need to check.
Have you tested for both with first_only and all?

**Comment by idxn** [comment]
Yes, I tested both and it currently run smoothly on my CI.

**Comment by idxn** [comment]
Any update on this? @serhatbolsu

**Comment by idxn** [comment]
@serhatbolsu Do you need me to update anything to get this merged?

**Comment by serhatbolsu** [comment]
Hey, I will check during this weekend

**Comment by idxn** [comment]
Sorry to reach out again. Is it possible to be merged?

**Comment by serhatbolsu** [comment]
@idxn can you share me the test case where you use this with passed an <WebElement> class and only need first result.
I will merge after this, willing to add to unit tests as well.

**Comment by idxn** [comment]
@serhatbolsu here is the example use case I have used 

`Get All Item Description
    ${items}=    AppiumLibrary.Get Webelements   ${locator}
    ${descs} =    Create List
    :FOR   ${item}    IN     ${items}
    \    ${desc}=   Get Element Attribute     ${item}    contentDescription
    \    Append To List     ${descs}   ${desc}
    [Return]    ${descs} `

**Comment by idxn** [comment]
@serhatbolsu For unittest, could you guide me how I can mock the webelement object? This is the first time i'm going to write the unittest from scratch so please shed me some light.

**Comment by idxn** [comment]
@serhatbolsu Any plan on this?

**Comment by serhatbolsu** [comment]
@idxn  I have pushed the fix for this issue
Unfortunately the fix you have provided was not the core of the issue. It was rather simple,
that ` _element_find` was not returning list where it should

```
    ${items}  get webelements  row_announcement_title
    ${descs}  Create List
    :FOR  ${item}  IN  @{items}
    \  ${desc}  get element attribute  ${item}  text
    \  Append To List  ${descs}  ${desc}
    Log To Console  ${descs}
```
Beware to use @{items} notation while running a for-in loop

**Comment by idxn** [comment]
@serhatbolsu That's quite a big change. Anyway, i'm pretty fine if it fixes mine though.

**Comment by serhatbolsu** [comment]
@idxn let me know if you are covered now. 
Not sure I got your comment though, it is already returning a list with first_only=False. 
```
${items}  get webelements  row_announcement_title
``` 
this representation is from robotframework but ${items} is an array

**Pull request closed without merging**
