### PR TITLE
Add Screen Record Keywords

### PR DESCRIPTION
**Pull request by joshuariveramnltech**
## Implements
* Screen Recording Keywords
  * **Start Screen Recording**
  * **Stop Screen Recording**

### CODE REVIEW

**Comment by serhatbolsu** [comment]
Thank you @joshuariveramnltech this looks very convincing. I dont have time to test yet, much appretiate if other's can test and comment here

**Comment by sidarakeo** [comment]
@joshuariveramnltech i will test it.

**Comment by HelioGuilherme66** [comment]
@serhatbolsu I have installed version 1.5.0.4, and I get errors for those two keywords, they don't exist.
```
>pip show robotframework-AppiumLibrary
Name: robotframework-appiumlibrary
Version: 1.5.0.4
Summary: Robot Framework Mobile app testing library for Appium Client Android & iOS & Web
Home-page: https://github.com/serhatbolsu/robotframework-appiumlibrary
Author: Serhat Bolsu, William Zhang, Xie Lieping, Jari Nurminen
Author-email: serhatbolsu@gmail.com,jollychang@gmail.com,frankbp@gmail.com
License: Apache License 2.0
Location: c:\program files\python37\lib\site-packages
Requires: docutils, selenium, Appium-Python-Client, decorator, robotframework, kitchen, six
Required-by:
```
Error is:
```
No keyword with name 'AppiumLibrary.Start Screen Recording' found.
```

**Comment by serhatbolsu** [comment]
You need to use the source code though, there is no released version with this code yet

**Comment by HelioGuilherme66** [comment]
OK. But the documentation includes the keywords already. Maybe it should mention "New since version 1.6" or similar. Thanks anyway.

**Comment by sidarakeo** [comment]
I've test on Samsung Galaxy S9+ (Android 10) it's can be record and saved as type (*.mp4) and test on iPhone 8 Plus (12.3.2) it's also work fine, But i have issue when test on Oppo F11 pro (Android 9) i got message : "

> Original error: The expected screen record file '/sdcard/1584674003307.mp4' does not exist after 5000ms. Is screenrecord utility available and operational on the device under test?

". 
I think there issue on Oppo device. 
Thanks you !!

**Comment by joshuariveramnltech** [comment]
hmmm, i think it is on the device, im also having a lot of trouble automating Oppo Devices.

Thanks @sidarakeo for testing it 👍

**Comment by sidarakeo** [comment]
@joshuariveramnltech one more when i try to save file as new name it's doesn't change.

  `Stop Screen Recording     NewName`

**Comment by joshuariveramnltech** [comment]
> @joshuariveramnltech one more when i try to save file as new name it's doesn't change.
> 
> `Stop Screen Recording NewName`
> i notice that you set static file name ?
> 
> ```
> def _get_screenrecord_paths(self, filename=None):
>         if filename is None:
>             self._screenrecord_index += 1
>             filename = '**appium-screenrecord-{index}.{ext}**'.format(index=self._screenrecord_index,
>                                                                   ext=self._output_format
>                                                                   )
> ```

the static name only applies when filename argument is not passed. otherwise, the filename you provided will be used.

**Comment by sidarakeo** [comment]
> > @joshuariveramnltech one more when i try to save file as new name it's doesn't change.
> > `Stop Screen Recording NewName`
> > i notice that you set static file name ?
> > ```
> > def _get_screenrecord_paths(self, filename=None):
> >         if filename is None:
> >             self._screenrecord_index += 1
> >             filename = '**appium-screenrecord-{index}.{ext}**'.format(index=self._screenrecord_index,
> >                                                                   ext=self._output_format
> >                                                                   )
> > ```
> 
> the static name only applies when filename argument is not passed. otherwise, the filename you provided will be used.

Yes but i try to giving filename but there still got None

**Comment by joshuariveramnltech** [comment]
Could you send here your robot script?

**Comment by sidarakeo** [comment]
> Could you send here your robot script?

Sorry it's was my bad. I forget to comment code in TearDown Script.Now it's work.

**Comment by f00dog-x300** [comment]
Any progress with merging this to the official build? Otherwise it's confusing to use this and see it not work.

**Comment by sidarakeo** [comment]
> Any progress with merging this to the official build? Otherwise it's confusing to use this from the documentation and see it not work.

Yes, seem not yet merge this.

**Comment by serhatbolsu** [comment]
@f00dog-x300 @sidarakeo new version released to pypi

**Pull request merged**
