### PR TITLE
add iOSNsPredicate location to elementfinder

### PR DESCRIPTION
**Pull request by lalamini**
just add iOSNsPredicate Location

### CODE REVIEW

**Comment by lalamini** [comment]
Hi manager，
I noticed that the CI build failed because the file test_request.txt is missing.
But , I have no test_request.txt file , so what can I do?
I just want the people can use nsp location as soon as possible, I find it's faster than any others.

Thanks!

**Comment by Kitty2014** [comment]
did Class Chain and Predicate release？ @lalamini

**Comment by trepository** [comment]
@lalamini , can you provide some examples on how to use the predicates with appiumlibrary. I tried but not working at all.

**Comment by lalamini** [comment]
iOSNsPredicate is a powerful tool for ios loctation
for name:  nsp=name=="login"
for type and name: nsp=type=="XCUIElementTypeImage" AND name=="login"
for re function : nsp=type=="XCUIElementTypeButton" AND name CONTAINS "monitor("
for begin with function : nsp=name BEGINSWITH "monitor("
for not equal: nsp=type=="XCUIElementTypeTextField" AND value!="100"
...
more type you should find it by yourself.  
Hope you enjoy it!

**Comment by MandyYdnam** [comment]
Any updates on its implementation in RF AppiumLibrary?

**Comment by lalamini** [comment]
The latest tag is 1.4.6 ， still without this function，you can use master branch to get it

**Comment by thepoppingone** [comment]
The current 1.5.0 version now has it but not reflected in the AppiumLibrary keyword documentation yet!

**Pull request merged**
