### PR TITLE
Upgrade to selenium 4 and python-client v2

### PR DESCRIPTION
**Pull request by serhatbolsu**
## Implements
Selenium Version 4 support and relative fixes for [python-client](https://github.com/appium/python-client)

## ToDO

- [x] Deprecate  TouchAction
- [x] Fix Launch App
- [x] Deprecate launch_app, close_app, reset_app
- [x] Fix documentation
- [x] strict_ssl = false option to open_application
- [x] Beta build
- [x] Support for arguments in `Execute Script`
- [x] Added new ActionHelper#tap method, refer to `Tap With Positions` 
- [x] Support for AppiumBy methods, and replacing find_element_by*
- [x] Added support for Espresso locators
- [x] iOS Test by Community
- [x] Android Test by Community
- [ ] Check locator strategies not to use `find_elements` for when ask is single element

❗️ Please test the beta build here ❗️ 
`pip install robotframework-appiumlibrary==2.0.0b5`

### CODE REVIEW

**Comment by atenwolde** [comment]
i have upgraded but now i got "AttributeError: 'WebDriver' object has no attribute 'find_elements_by_ios_class_chain'"

**Comment by serhatbolsu** [comment]
@atenwolde checking it, thank you, it seems selenium 4 also changed the locators

**Comment by serhatbolsu** [comment]
@atenwolde  please test again, if you can with iOS. in b4 package I just uploaded

**Comment by atenwolde** [comment]
> @atenwolde please test again, if you can with iOS. in b4 package I just uploaded

I have tested it with th b4 package and it works. Thanks for you quick respons

**Comment by js361014** [comment]
In [AppiumLibrary/keywords/_applicationmanagement.py](https://github.com/serhatbolsu/robotframework-appiumlibrary/pull/363/files#diff-0d6557c5bbccf1e078812231c709f13852caab80944e2ff3a7c4f7d3c8ac9397)
`remove_application` is declared twice at line 138 and 300

**Comment by js361014** [comment]
in `AppiumLibrary/keywords/_element.py` function `def click_button(self, index_or_name):` produces `AttributeError: 'WebDriver' object has no attribute 'find_elements_by_class_name'`

**Comment by serhatbolsu** [comment]
@js361014 Thank you for your testing, updated all the rest of the find_element_by type methods. please re-test

**Comment by serhatbolsu** [comment]
I will release the v2.0 if there is not further testing / issues found until tomorrow

**Comment by robco** [comment]
Hi. Can you check whether it works with Selenium Grid?

I have troubles running it. Seems Selenium Hub is never reached by the new AppiumLibrary (tried versions: 2.0.0b5, 1.6.4). 1.6.3 is working just fine. There is no Selenium Hub indication in the logs that any external connection/test request is coming to it. 

Selenium Hub version: 4.5.3
Selenium Node version: 4.5.3
Appium version on Node: 1.22.3

RF demo test:

```
*** Settings ***

Library  AppiumLibrary

Suite Setup     Open my app
Suite Teardown  Close All Applications

Test Teardown   Quit Application


*** Variables ***

${SELENIUM_GRID_HUB_URL}  http://MY_HUB_IP:4444/wd/hub
${PLATFORM_NAME}   iOS
${PLATFORM_VERSION}  16.0
${DEVICE_NAME}   iPad (9th generation)
${AUTOMATION_NAME}  XCUITest
${APPLICATION_BUNDLE}   https://path.to.my.build.repo.com/BUILDS/ROBOT/my_app.zip


*** Keywords ***

Open SMART app
   Open Application  ${SELENIUM_GRID_HUB_URL}  platformName=${PLATFORM_NAME}  platformVersion=${PLATFORM_VERSION}  deviceName=${DEVICE_NAME}  app=${APPLICATION_BUNDLE}  automationName=${AUTOMATION_NAME}
   Sleep  5s


*** Test Cases ***

Open application
   Launch Application
```

**Error seen:**
```
SessionNotCreatedException: Message: Could not start a new session. New session request timed out 
Host info: host: 'lctcvp6240', ip: '54.56.168.73'
Build info: version: '4.5.3', revision: '4b786a1e430'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.59.1.el7.x86_64', java.version: '17.0.1'
Driver info: driver.version: unknown
```

**Comment by serhatbolsu** [comment]
@robco  thank you for your results, I have done a test with saucelabs , it seems to be working fine, check my desiredCapabilities below

```
Open iOS Sauce Test App
  &{SAUCE_OPTIONS}  create dictionary    appiumVersion=2.0.0-beta44
  open application  ${IOS_SAUCE_URL}  platformName=${IOS_PLATFORM_NAME_SAUCE}
  ...  appium:app=${IOS_APP_SAUCE}  appium:deviceName=${IOS_DEVICE_NAME_SAUCE}
  ...  appium:platformVersion=${IOS_PLATFORM_VERSION_SAUCE}  appium:automationName=${IOS_AUTOMATION_NAME_SAUCE}
  ...  deviceName=${IOS_DEVICE_NAME_SAUCE}  sauce:options=&{SAUCE_OPTIONS}
```

url is something like `http://<<sauce_user:sauce_key>>:url:443/wd/hub`

**Comment by serhatbolsu** [comment]
Since also tested with appium version `2.0.0-beta44` on iOS too, releasing now, thank you for all contributions

**Comment by robco** [comment]
@serhatbolsu, can you provide your RF test? All I am changing is just the AppiumLibrary version through PiP and I see 100% reproducible issue with "tests not getting pushed to grid". Tried macOS, ubuntu (native and in docker)..

**Comment by serhatbolsu** [comment]
@Robert Seege ***@***.***>

here is the test


*** Settings ***
Resource  ../resources/resource.robot
Test Setup  Open iOS Sauce Test App
Test Teardown  Close Application


*** Keywords ***
Open iOS Sauce Test App
  &{SAUCE_OPTIONS}  create dictionary    appiumVersion=2.0.0-beta44
  open application  ${IOS_SAUCE_URL}  platformName=${IOS_PLATFORM_NAME_SAUCE}
  ...  appium:app=${IOS_APP_SAUCE}  appium:deviceName=${IOS_DEVICE_NAME_SAUCE}
  ...  appium:platformVersion=${IOS_PLATFORM_VERSION_SAUCE}
appium:automationName=${IOS_AUTOMATION_NAME_SAUCE}
  ...  deviceName=${IOS_DEVICE_NAME_SAUCE}  sauce:options=&{SAUCE_OPTIONS}


*** Test Cases ***
Should find elements by ID
  ${element}  get webelement  ComputeSumButton
  element should be visible  ${element}

**Comment by robco** [comment]
Thank you. Tried that, too.

Only difference in mine is I do not use SauceLabs but local Selenium Grid setup, v4.5.3 (the latest version).

When I change AppiumLibrary version from 1.6.3 to something above it just never seems to ping hub and execution times out as in my previous comment..

The only physical change between AppiumLibrary 1.6.3 and AppiumLibrary 2.0.0 in my system are the versions of the dependences resolved automatically by PiP: 

AppiumLibrary 1.6.3: Appium-Python-Client-1.3.0 robotframework-appiumlibrary-1.6.3 selenium-3.141.0
AppiumLibrary 2.0.0: Appium-Python-Client-2.7.1 robotframework-appiumlibrary-2.0.0 selenium-4.5.0

**Comment by serhatbolsu** [comment]
Likely its about the appium version then

**Comment by serhatbolsu** [comment]
@robco please create a new issue with your case and environment again, I will investigate

**Comment by robco** [comment]
@serhatbolsu, I've just created #367 for this. Thank you.

**Pull request merged**
